## Comment out when doing local development
backend:
  name: github
  repo: GSA-TTS/tts.gsa.gov
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main
  use_graphql: true

##
## Uncomment when doing local development on Netlify CMS
## Run `npx netlify-cms-proxy-server` to start working locally
## In another terminal, start the app with `npm start`
## See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
##

# backend:
#   name: git-gateway
# local_backend: true

media_folder: _img
public_folder: _img
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Posts
    name: posts
    folder: posts/
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'layouts/post'}
      - {label: 'Tags', name: 'tags', widget: 'hidden', default: ['posts']}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: 'YYYY-MM-DD',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: false
        }
      - {
        label: "Image",
        name: "image",
        widget: "image",
        allow_multiple: false,
        required: false
        }
      - {
        label: "Image Alt Text",
        name: "image_alt_text",
        widget: "string",
        required: false
        }
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Services Page"
    name: Services
    create: true
    format: "yaml"
    files:
      - label: "Services"
        name: "services"
        file: "_data/services.yaml"
        fields:
          - label: "Services"
            name: "services"
            widget: "list"
            label_singular: "service"
            order: "{{fields.name}}"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Link, name: link, widget: string}
              - {label: Link Alt Text, name: link_alt_text, widget: string}
              - {label: Logo, name: logo, widget: image}
              - {label: Logo Alt Text, name: logo_alt_text, widget: string}
              - {label: Category, name: category, widget: string}
              - {label: Description, name: description, widget: text}
  - label: "Jobs Page"
    name: Jobs
    create: true
    folder: pages/jointts/positions
    slug: "{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Page Link, name: permalink, widget: string}
      - {label: Tags, name: tags, widget: string}
      - {label: Job State, name: state, widget: "select", options: ["closed", "open", "upcoming"]}
      - {label: Job Post Type, name: job_post_type, widget: string}
      - {label: Role Name, name: role_name, hint: "Required for upcoming", widget: string}
      - {label: Open Date, name: opens, hint: "Required for upcoming", widget: string}
      - {label: Close Date, name: closes, hint: "Required for upcoming", widget: string}
      - {label: Weeks Open, name: weeks_open, hint: "Required for upcomfing", widget: number}
      - {label: Location, name: location, hint: "Required for upcoming", widget: string}
      - {label: GS Level, name: gs_level, hint: "Required for upcoming", widget: string}
      - {label: Mininum Salary, name: salary_min, hint: "Required for upcoming", widget: string}
      - {label: Maximum Salary, name: salary_max, hint: "Required for upcoming", widget: string}
      - {label: Organization, name: org, hint: "Required for upcoming", widget: string}
      - {label: Contact Name, name: contact_name, hint: "Required for upcoming", widget: string}
      - {label: Contact Email, name: contact_email, hint: "Required for upcoming", widget: string}
      - {label: Job Announcement Number, name: job_announcement_number, hint: "Required for open", widget: string}
      - {label: PD Job Title, name: pd_job_title, hint: "Required for open", widget: string}
      - {label: Number of Vacancies, name: num_vacancies, hint: "Required for open", widget: number}
      - {label: series, name: series, hint: "Required for open", widget: string}
      - {label: Application URL, name: apply_url, hint: "Required for open", widget: string}
      - {label: OHRM Contact Email, name: ohrm_contact_email, hint: "Required for open", widget: string}
      - {label: OHRM Contact Name, name: ohrm_contact_name, hint: "Required for open", widget: string}
      - {label: Bargaining Unit, name: bargaining_unit, hint: "Required for open", widget: string}
      - {label: Promotion Potential, name: promotion_potential, hint: "Required for open", widget: number}
      - {label: Supervisory Status, name: supervisory_status, hint: "Required for open", widget: "select", options: ["no", "yes"]}
      - {label: "Body", name: "body", widget: "markdown"}
